##############################################################################
# ★ TERRAGON AUTONOMOUS SDLC VALUE DISCOVERY CONFIGURATION ★
##############################################################################
# Photonic Neuromorphics Repository - Advanced Maturity Level (75%+)
# Continuous value discovery and autonomous execution system
##############################################################################

repository:
  name: "photonic-neuromorphics-sim"
  maturity_level: "advanced"  # 75%+ SDLC maturity
  technology_stack: "python_scientific"
  domain: "photonic_neuromorphics"
  primary_language: "python"
  framework: "pytorch"
  created: "2025-01-15T00:00:00Z"
  last_assessment: "2025-08-01T00:00:00Z"

##############################################################################
# VALUE SCORING CONFIGURATION (Advanced Repository Weights)
##############################################################################
scoring:
  weights:
    advanced:  # Repository maturity level
      wsjf: 0.5            # Weighted Shortest Job First
      ice: 0.1             # Impact, Confidence, Ease
      technical_debt: 0.3  # Higher focus on debt in mature repos
      security: 0.1        # Continuous security improvements
  
  thresholds:
    min_score: 15.0        # Higher threshold for advanced repos
    max_risk: 0.7          # Lower risk tolerance
    security_boost: 2.0    # Security work gets 2x priority
    compliance_boost: 1.8  # Compliance work gets 1.8x priority
    performance_boost: 1.5  # Performance optimization priority

  penalties:
    documentation_only: 0.6    # Documentation work gets 60% weight
    dependency_update: 0.8     # Dependency updates get 80% weight
    code_cleanup: 0.7         # Cleanup tasks get 70% weight

##############################################################################
# DISCOVERY SOURCES AND TOOLS
##############################################################################
discovery:
  sources:
    git_history:
      enabled: true
      keywords: ["TODO", "FIXME", "XXX", "HACK", "DEPRECATED", "temp", "quick fix"]
      commit_message_patterns: ["temp", "quick", "hack", "wip", "fix"]
      
    static_analysis:
      enabled: true
      tools: ["ruff", "mypy", "bandit", "vulture"]
      complexity_threshold: 10
      
    security_scanning:
      enabled: true
      tools: ["safety", "bandit", "semgrep"]
      vulnerability_sources: ["osv", "ghsa", "nvd"]
      
    performance_monitoring:
      enabled: true
      regression_threshold: 0.05  # 5% performance regression
      memory_threshold: 1.1       # 10% memory increase
      
    issue_tracking:
      enabled: true
      sources: ["github_issues", "github_prs"]
      include_closed: false
      max_age_days: 90

  file_patterns:
    source_code: ["**/*.py", "**/*.pyx"]
    configuration: ["**/*.yaml", "**/*.yml", "**/*.toml", "**/*.ini"]
    documentation: ["**/*.md", "**/*.rst", "docs/**/*"]
    tests: ["tests/**/*.py", "**/*test*.py"]
    infrastructure: ["Dockerfile", "docker-compose*.yml", ".github/**/*"]

##############################################################################
# EXECUTION CONFIGURATION
##############################################################################
execution:
  max_concurrent_tasks: 1
  batch_processing: false
  
  validation:
    run_tests: true
    min_coverage: 80
    performance_regression_limit: 0.05
    security_scan_required: true
    
  rollback_triggers:
    - "test_failure"
    - "build_failure" 
    - "security_violation"
    - "performance_regression"
    - "coverage_decrease"

  branch_naming: "auto-value/{item_id}-{slug}"
  pr_labels: ["autonomous", "value-driven"]
  
##############################################################################
# DOMAIN-SPECIFIC CONFIGURATION (Photonic Neuromorphics)
##############################################################################
domain_specific:
  photonic_neuromorphics:
    file_extensions: [".py", ".sp", ".v", ".sv", ".gds", ".lef"]
    
    performance_metrics:
      simulation_time: 300.0      # seconds
      memory_usage: 2048          # MB
      convergence_tolerance: 1e-6
      
    quality_gates:
      spice_simulation_pass: true
      rtl_synthesis_clean: true
      layout_drc_clean: true
      
    specialized_tools:
      eda: ["magic", "ngspice", "yosys", "openlane"]
      photonic: ["gdspy", "spicepy", "lumerical"]
      neural: ["torch", "numpy", "scipy"]

##############################################################################
# CONTINUOUS LEARNING CONFIGURATION  
##############################################################################
learning:
  feedback_loop:
    enabled: true
    accuracy_threshold: 0.8    # 80% prediction accuracy required
    adjustment_factor: 0.1     # 10% weight adjustment per iteration
    
  model_updates:
    frequency: "weekly"
    retention_period: "6months"
    min_samples: 10
    
  pattern_recognition:
    enabled: true
    similarity_threshold: 0.85
    context_window: 30  # days

##############################################################################
# AUTOMATED SCHEDULING
##############################################################################
schedule:
  immediate:
    triggers: ["pr_merged", "main_branch_push", "release_created"]
    max_execution_time: "30min"
    
  periodic:
    hourly:
      tasks: ["security_scan", "dependency_check"]
      enabled: true
      
    daily: 
      tasks: ["static_analysis", "performance_check", "debt_assessment"]
      time: "02:00"
      enabled: true
      
    weekly:
      tasks: ["deep_analysis", "architecture_review", "dependency_updates"]
      day: "monday"
      time: "03:00"
      enabled: true
      
    monthly:
      tasks: ["strategic_review", "model_recalibration", "metrics_analysis"]
      day: 1
      time: "04:00"
      enabled: true

##############################################################################
# REPORTING AND METRICS
##############################################################################
reporting:
  backlog_file: "BACKLOG.md"
  metrics_file: ".terragon/value-metrics.json"
  history_file: ".terragon/execution-history.json"
  
  dashboard:
    enabled: true
    refresh_interval: "1hour"
    retention_days: 90
    
  notifications:
    high_value_items: true
    security_alerts: true
    performance_regressions: true
    completion_summaries: true

##############################################################################
# INTEGRATION SETTINGS
##############################################################################
integrations:
  github:
    auto_assign_reviewers: true
    use_codeowners: true
    require_approval: true
    
  monitoring:
    prometheus_metrics: true
    structured_logging: true
    trace_execution: true
    
  ci_cd:
    trigger_builds: true
    wait_for_success: true
    auto_merge_safe: false  # Conservative approach for advanced repos

##############################################################################
# ADVANCED FEATURES (For Mature Repositories)
##############################################################################
advanced_features:
  architecture_analysis:
    enabled: true
    complexity_metrics: true
    coupling_analysis: true
    hotspot_detection: true
    
  modernization_tracking:
    enabled: true
    technology_debt: true
    framework_updates: true
    best_practices: true
    
  compliance_monitoring:
    enabled: true
    security_standards: ["OWASP", "NIST"]
    quality_gates: true
    audit_trails: true
    
  optimization_focus:
    performance: true
    maintainability: true
    scalability: true
    security: true

##############################################################################
# VERSION AND METADATA
##############################################################################
version: "1.0.0"
schema_version: "2025.1"
last_updated: "2025-08-01T00:00:00Z"
created_by: "terragon-autonomous-sdlc-v1.0"